### ISSUE TITLE
Upload image from /modules/suico/album.php

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#127]
Result in /modules/suico/submitImage.php
Error : TypeError: imagesx() expects parameter 1 to be resource, bool given

But it adds +1 to the badge "Photos"
But i dont see any photo.

alain01 : Ok for me now !

**Comment by liomj** [comment]
Reported by alain

**Comment by mambax7** [comment]
While line was this error on?

**Comment by liomj** [comment]
@alain01 reported it is solved
