### ISSUE TITLE
error when enable guest acccess

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#143]
Notice: Undefined variable: friendController in file /modules/suico/index.php line 300
Notice: Trying to get property 'uidOwner' of non-object in file /modules/suico/index.php line 300
Notice: Undefined variable: friendController in file /modules/suico/index.php line 301
Notice: Trying to get property 'friendshipsFactory' of non-object in file /modules/suico/index.php line 301
Error: Error: Call to a member function getFriends() on null in file /modules/suico/index.php line 301

**Comment by alain01** [comment]
yes, i've just see that, you are quicker than me ;-)

**Comment by mambax7** [comment]
Do we want to enable Guess Access?

**Comment by alain01** [comment]
There is an option in preferences, so we can do it!

**Comment by mambax7** [comment]
Fixed

**Comment by alain01** [comment]
No,
no blank page but a page without any css files definition

**Comment by mambax7** [comment]
It looks perfect here:
![image](https://user-images.githubusercontent.com/613686/80914679-1a1d9080-8d1b-11ea-843e-8efe84e46d29.png)

**Comment by alain01** [comment]
Argg,
yes, with cleaned browser cache, yes ! 
That's sound good ! 
But,
why by default , the admin's profile page ? (it's a very minor question)

**Comment by mambax7** [comment]
Alain, please submit it request for a "welcome page" as an enhancement.

**Comment by mambax7** [comment]
OK, LioMJ did it already: https://github.com/XoopsModules25x/suico/issues/148
