### ISSUE TITLE
Error: Class 'XoopsModules/Suico/ImageHandler' not found

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#147]
Error: Class 'XoopsModules/Suico/ImageHandler' not found in file /modules/suico/blocks/photos_block.php line 50

1. enable photo block
2. Update the module
3. refresh main page
4. error

**Comment by mambax7** [comment]
See if https://github.com/XoopsModules25x/suico/pull/149 fixed that

**Comment by mambax7** [comment]
If there are no more bugs, then let's release it as a Beta 1 :)

**Comment by liomj** [comment]
> If there are no more bugs, then let's release it as a Beta 1 :)

another one bug found https://github.com/XoopsModules25x/suico/issues/150

**Comment by alain01** [comment]
> If there are no more bugs, then let's release it as a Beta 1 :)

Hum, i didnt test all in this module cause Lio works quicker than i can test ;-)
So, tell me when your dev seems to be fine, (i mean "not 10 merge / day) then
let me 24/48h to test all i can test in this module !

**Comment by mambax7** [comment]
Don't worry about it - this is just a Beta, i.e. that's when the real testing begins :) 
I just need to fix the "sample data" and once it works, I'll release it in the next couple of hours. 
Unless somebody discovers some serious bugs!
