### ISSUE TITLE
sample data problem for guest access

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#150]
1. enable guest access
2. Import sample data
3. Logout
4. access localhost/25/modules/suico
5. redirected to localhost

**Comment by mambax7** [comment]
The sample data will be changed as there were conflicts. So ignore the import for now, and just test everything else

**Comment by liomj** [comment]
noted mamba ..
by the way the error with profile visitor still present https://github.com/XoopsModules25x/suico/issues/30
