### ISSUE TITLE
Editor Preferences :: Editor: Admin

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/suico#156]
Please, by default, for installation, 
for the editor for admin groups : enable DHTML, not TinyMCE

**Comment by mambax7** [comment]
Come on, Alain, everybody is using HTML editors! Let's not make XOOPS look old :)

**Comment by mambax7** [comment]
Alain, you have the option to change it for yourself in the Preferences:
![image](https://user-images.githubusercontent.com/613686/80921185-d2aafa80-8d42-11ea-91b9-0e4e53e94f94.png)

**Comment by alain01** [comment]
Better to use DHTML,
TinyMCe, this version is old, and really old fashion style ! 
![Annotation 2020-05-03 193647](https://user-images.githubusercontent.com/5336960/80921248-80370180-8d75-11ea-9661-5940287cf7ec.png)

See the site monxoops.fr 
Do you think i use tinyMCE ? No, 
Better is to use clean code,
so i say again : preference by defautl for all, for the installation should be DHTML.

In fact, webmaster use clean HTML (to use BT4 for exemple), IMPOSSIBLE with Tiny,
With DHTML, u can type a clean code to produce EXACTLY what u want.
Hope you understand my opinion, now

**Comment by mambax7** [comment]
That's why we have to move to TinyMCE 5 :) 
You should update your [TinyMCE4](https://github.com/alain01/TinyMCE4forXOOPS) with this Bootstrap plugin and then update it to Bootstrap 4 and TinyMCE 5:
https://github.com/migliori/tinymce-bootstrap-plugin

I agree that TinyMCE 3 that we have is outdated. But we can't compete against other CMS systems by using old technologies. New users want to use WYSIWYG Editors, not learn BB Codes...

**Comment by mambax7** [comment]
BTW - I started to work on it, but ran out of time and didn't finish it:
https://github.com/mambax7/xoopseditors/tree/master/htdocs/class/xoopseditor/tinymce4bootstrap
You might try to finalize it, or move directly to TinyMCE 5

**Comment by alain01** [comment]
Humm
i remember i tried to integrate Tmce v4 in xoops, but i stopped cause it was too hard for me.
Ok, i will try just 2 or 3 days max with v5.
May be i can use your code (for v4) to start this ?

**Comment by mambax7** [comment]
Of course!!!  After all, I used yours as the base... :)

**Comment by alain01** [comment]
you mean, mine, v3 (from an existant v2)
you, v4 (not finished) from mine,
me, from your v4 ?
Hope v6 will come early ! 
That will be your turn !

**Comment by alain01** [comment]
Hey,
good start, 1st tests, it runs ! 
I need to customize now!

**Comment by mambax7** [comment]
Excellent! I'm glad that it is working...
