### ISSUE TITLE
User setting Issues

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#159]
we should test this thoroughly because of user privacy

i found some issues

1. when we set info to only me, other user still can see the website in navbar

**Comment by liomj** [comment]
2. when user set only me for photos, photos uploaded by user is listed is photo block

**Comment by liomj** [comment]
Mamba what is the reason for friends privacy settings to have only 2 options?

**Comment by mambax7** [comment]
Because it was crashing the module when you set up friends to Only Me or to Friends only. 
We'll need to rewrite it later for Beta 2, but right now there was time to do it...

**Comment by mambax7** [comment]
> when we set info to only me, other user still can see the website in navbar
This should be fixed by now

I'll be looking now at the block pictures

**Comment by mambax7** [comment]
The block pictures should be now fixed:
https://github.com/XoopsModules25x/suico/pull/168
