### ISSUE TITLE
Handler not found

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#170]
'XoopsModules/Suico/ImageHandler' not found in file /modules/suico/blocks/photos_block.php line 48

Error: Error: Class 'XoopsModules/Suico/FriendshipHandler' not found in file /modules/suico/blocks/friends_block.php line 51

**Comment by mambax7** [comment]
When does it happen? At what URL? Or is it all the time? 
It works fine here.

**Comment by liomj** [comment]
When updating the module in admin..then refresh main page with blocks activated

**Comment by mambax7** [comment]
I still can't reproduce it :( 
Can you try with the new sample data? 
Please note - I've added now extra users for testing, they will be added as part of the import of the sample data
