### ISSUE TITLE
Recent Visitors in Profile not working

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#30]
Recent Visitors in Profile not working

**Comment by mambax7** [comment]
It seems to be working, i.e. I was able to save the visitor info, but I'm still not sure how to actually present it to the user. Or is it going to be only for the Admin? 
![image](https://user-images.githubusercontent.com/613686/80914390-39b3b980-8d19-11ea-9a90-37014dcf8eee.png)

**Comment by liomj** [comment]
> It seems to be working, i.e. I was able to save the visitor info, but I'm still not sure how to actually present it to the user. Or is it going to be only for the Admin?
> ![image](https://user-images.githubusercontent.com/613686/80914390-39b3b980-8d19-11ea-9a90-37014dcf8eee.png)

this is still not fixed ..it supposed to appear in profile theres code in the templates

**Comment by mambax7** [comment]
That's what I didn't know what to do with it - pointing out to the template is helpful, hopefully we can make it work :)

**Comment by mambax7** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/613686/80916766-c619a880-8d28-11ea-81dc-763be376f4b2.png)
