### ISSUE TITLE
Online status always offline

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#31]
In index and memberslist and searchmembers result

**Comment by liomj** [comment]
I'm having this issue, when my online status will always show offline even when im online but today
i tried in another pc laptop, it seems the status is working alright

Trying to figure this out what might cause this

**Comment by alain01** [comment]
Browser cache ?

**Comment by liomj** [comment]
maybe but i i tried with browser private and incognito mode..same problem

**Comment by mambax7** [comment]
I've seen it too. I'll check it, maybe I'll find something...

**Comment by liomj** [comment]
https://github.com/XOOPS/XoopsCore25/issues/491

**Comment by mambax7** [comment]
I think, we can close it, since on my regular host it is working:
![image](https://user-images.githubusercontent.com/613686/80678225-8339a580-8a88-11ea-9f0c-6c3a62a908a8.png)
