### ISSUE TITLE
Proportional resizing of images

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/suico#80]
We'll need to find a way to resize them proportionally, or enforce the same size for logos at the submission time
![image](https://user-images.githubusercontent.com/613686/80288658-55123980-8707-11ea-9948-62fc578bb0ab.png)

**Comment by liomj** [comment]
When we have the original image inserted in the database like in album it will look much better

Maybe thumnail can be set to 250x250

**Comment by liomj** [comment]
i moticed that when uploading the group image the height of image is set to auto

**Comment by mambax7** [comment]
That looks better now:
![image](https://user-images.githubusercontent.com/613686/80744205-5028fd80-8aec-11ea-9ab1-1bde25204a9e.png)
