### ISSUE TITLE
Picture Block is too wide

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/suico#87]
The block tends to be too wide, overlapping the main screen:
![image](https://user-images.githubusercontent.com/613686/80476532-831a9800-8918-11ea-9dfd-368912a1285a.png)

**Comment by mambax7** [comment]
Now it looks better:
![image](https://user-images.githubusercontent.com/613686/80748672-4ce54000-8af3-11ea-8578-b274d6d6a19e.png)

**Comment by mambax7** [comment]
This is not looking good :( 
![image](https://user-images.githubusercontent.com/613686/80829714-a6ae3e80-8bb5-11ea-97e8-bbd33d93030d.png)

**Comment by liomj** [comment]
![Untitled](https://user-images.githubusercontent.com/16532279/80845739-ba50b800-8c3c-11ea-947c-a4b1b8fdb295.jpg)
