### ISSUE TITLE
errors during registration

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/suico#97]
Error: TypeError: uniqid() expects parameter 1 to be string, int given in file /modules/suico/user.php line 250

**Comment by mambax7** [comment]
I don't see any issues during installation.

**Comment by liomj** [comment]
i receive this error here trying to register as a new user

/modules/suico/user.php?op=register

**Comment by liomj** [comment]
Fix https://github.com/XoopsModules25x/suico/commit/49056aa770c1bd3c02c69d1a6073bb7f5482f82a
